Traceback (most recent call last):
  File "auto_update.py", line 69, in <module>
    closed_sql = f.read()
  File "C:\Users\chienchenghung\AppData\Local\Programs\Python\Python38\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xab in position 125: invalid start byte
